export const FETCH_CART_START = 'cart/FETCH_CART_START';
export const FETCH_CART_SUCCESS = 'cart/FETCH_CART_SUCCESS';
export const FETCH_CART_ERROR = 'cart/FETCH_CART_ERROR';
export const ADD_CART_ITEM_START = 'cart/ADD_CART_ITEM_START';
export const ADD_CART_ITEM_SUCCESS = 'cart/ADD_CART_ITEM_SUCCESS';
export const ADD_CART_ITEM_ERROR = 'cart/ADD_CART_ITEM_ERROR';